# 컴포즈 버전
version: '3.8'
# 컨테이너
services:
  # 서비스 명
  mongodb:
    # 이미지 (비트나미 몽고)
    image: bitnami/mongodb:latest
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름
    container_name: openai-study
    # 접근 포트(외부:컨테이너 내부)
    ports:
      - '37017:27017'
    # -e 옵션
    environment:
      # MongoDB 계정 및 패스워드
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=coco123!
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      # -v 옵션 (다렉토리 마운트 설정)
      - ./mongo-data/db:/data/db
# ------------------------------------------
# 실행
#   docker-compose up -d

# 컴파스 등 몽고 디비 접속 방법
#   mongodb://root:coco123!@127.0.0.1:37017/gpt?authSource=admin&directConnection=true